### ISSUE TITLE
Problème avec l'intégration css dans la requete / champ data

### ISSUE THREAD

**Issue by nicolas-aucourt** [quadra-informatique/Atos-Magento#9]
Bonjour,

Je cherche à envoyer une information dans le champ data. Cela concerne l'url d'un fichier css permettant de personnaliser les templates de base du serveur bancaire.

La documentation officiel donne l'exemple suivant:
$parm="$parm data=<USE_CSS>;https://www.test.fr/css/fichier.css</USE_CSS>;";

J'ai donc cherché à modifier le fichier suivant:
app/code/community/Quadra/Atos/Model/Method/Standard.php

à la ligne 60:
$parameters .= " data=<USE_CSS>\;http://skin.mamatoro.com/frontend/ultimo/default/css/mamatoro.css</USE_CSS>\;" . str_replace(',', '\;', $this->getConfig()->getSelectedDataFieldKeys());

Quand je me retrouve à l'url suivante: http://www.mamatoro.com/fr/atos/payment_standard/redirect/
J'ai cette erreur:
Please, select your payment method:

Call request file error

Executable file request not found (/home/mamatoro/www/prod/lib/atos/bin/request)

Une fois que j'enlève ce fameux USE_CSS, tout rentre dans l'ordre...

Est-ce que votre module "gère" cette directive un peu spécial? Le support à l'air de me dire que cela viendrait plus de mon code...

Merci beaucoup si vous pouvez débloquer la situation.

Bien cordialement,
Nicolas AUCOURT

**Comment by BenjaminPiscart** [comment]
Bonjour je suis confronté au meme problème quelle syntaxe as tu utilisé ?
Mon exemple en php non fonctionnel:
$parm = "$parm DATA=<USE_CSS>;mon.css</USE_CSS>;";

**Comment by mpasquin** [comment]
Bonjour,

D'après la documentation de l'API d'Atos, le fichier css à utiliser pour personnaliser les templates de paiement doivent être fournis à votre banque pour qu'ils soient héberger sur le serveur de paiement.

Il faut ensuite remplacer la ligne 
$parameters .= " data=" . str_replace(',', '\;', $this->getConfig()->getSelectedDataFieldKeys());
par
$parameters .= " data=**<USE_CSS>\;nom_du_fichier_css</USE_CSS>\;**" . str_replace(',', '\;', $this->getConfig()->getSelectedDataFieldKeys());
dans le fichier app/code/community/Quadra/Atos/Model/Method/Standard.php 

Vous pouvez faire de même pour toutes les méthodes de paiement que vous utilisez.

L'important est de bien échapper le point virgule avec un anti-slash : **\;**
Sinon cela ne fonctionne pas.

J'espère avoir correctement répondu à votre question.

Cordialement.
